config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    collection do
      get 'search', to: 'users#search'
    end
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resources :questions, only: [:index, :show, :create, :new, :destroy] do
      resources :answers, only: [:index,:create, :destroy]
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # Define your root route
  root to: 'pages#home'
  get '/users/:user_id/questions/:question_id/answers/new', to: 'answers#new', as: 'new_user_question_answer'
end

app/models/answer.rb
class Answer < ApplicationRecord
  # relations
  belongs_to :user
  belongs_to :question
  # validations
  validates :content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  # relations
  belongs_to :user
  belongs_to :asker, class_name: 'User', foreign_key: 'user_id'
  belongs_to :asked_to, class_name: 'User', foreign_key: 'asked_to_id', optional: true
  has_many :answers, dependent: :destroy
  # validations
  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validations
  validates :username, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  # relations
  has_one_attached :photo
  has_many :questions
  has_many :answers
  has_many :asked_questions, class_name: 'Question', foreign_key: 'asked_to_id'

  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # search
  include PgSearch::Model
  pg_search_scope :search_by_username,
    against: %i[ username first_name last_name ],
    using: {
      tsearch: { prefix: true }
    }


  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question, only: %i[index create destroy]
  def index
    @answer = Answer.new
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    if @answer.save
      redirect_to user_path(current_user), notice: 'Answer created successfully.'
    else
      redirect_to user_path(current_user), alert: 'Failed to create answer.'
    end
  end

  def new
    @answer = Answer.new
    @user = User.find(params[:user_id])
    @question = Question.find(params[:question_id])
  end

  private

  def answer_params
    params.require(:answer).permit(:content, :question_id)
  end

  def set_question
    @question = Question.find(params[:question_id])
    @user = @question.user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name username])

    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name username])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  def index
    @questions = Question.all
    @questions = current_user.asked_questions
    @answer = Answer.new
  end

  def show
    @user = User.find(params[:id])
    @questions_asked_to_user = @user.asked_questions
    @question = Question.find(params[:question_id])
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.asker = current_user
    @question.asked_to_id = params[:question][:asked_to_id]
    @question.anonymous = params[:question][:anonymous] == '1'

    if @question.save
      redirect_to users_path(current_user), notice: 'Question sent successfully.'
    else
      redirect_to users_path(current_user), notice: 'Sorry, there was an issue.'
    end
  end

  def destroy
    @question = current_user.questions.find(params[:id])
    @question.destroy
    redirect_to user_path(current_user), notice: 'Question deleted successfully.'
  end

  private

  def question_params
    params.require(:question).permit(:content, :asked_to_id).merge(asker_id: current_user.id)
  end

  def set_user_and_question(question)
    @user = question.asked_to_user
    @question = question
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  def create
    user = User.find(params[:user_id])
    current_user.follow(user)
    redirect_to request.referer
  end

  def destroy
    user = User.find(params[:user_id])
    current_user.unfollow(user)
    redirect_to  request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:follow, :unfollow]
  before_action :set_user, only: [:show, :edit, :update]

  def index
    @users = User.all
  end

  def show
    @question = @user.questions.new if current_user
    @answers = @user.answers
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def search
    @users = User.search_by_username(params[:query])
    render 'search'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :photo, :query)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= simple_form_for [@user, question, answer], url: user_question_answers_path(@user, question), method: :post do |f| %>
  <%= f.text_area :content, id: "answer_content", name: "answer[content]", required: true %>
  <%= f.hidden_field :asked_to_id, value: @user.id %>
  <div class="submit-question">
    <div class="answer-button">
      <%= f.button :submit, 'answer', class: 'submit-btn' %>
    </div>
  </div>
<% end %>

app/views/answers/new.html.erb
<div class="answer-container">
  <h2>Answer Question</h2>
  <%= render 'form', question: @question, answer: @answer %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AskFizz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon" href="askfizz.ico">
    <%= favicon_link_tag 'askfizz.ico' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <%= image_tag('home.png', class:"home-pic") %>
  <div class="description">
    <p>Explore AskFizzーThe versatile platform offering you the choice to share openly or ask questions anonymously.
      Dive into authentic conversations, connecting with a community that embraces both visibility and mystery.</p>
    <% if user_signed_in? %>
      <h3>Welcome, <%= current_user.username %>!</h3>
    <% else %>
      <button id="signin-button">
        <%= link_to "Sign-in", new_user_session_path %>
      </button>
    <% end %>
  </div>
</div>
<div class="card-container">
  <%= image_tag "laptop.png", style: "height: 260px;" %>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Ask Anonymously</h5>
      <h6 class="card-subtitle mb-2 text-muted"><i class="fa-regular fa-user"></i> <i class="fa-regular fa-user"></i> <i class="fa-regular fa-user"></i></h6>
      <p class="card-text">Discover the power of hidden curiosity on AskFizz! Ask Anonymously and transform your questions into whispered wonders. Delve into a world where secrets are safe,
        and curiosity knows no boundaries. Your identity, your questions – a mysterious symphony on the canvas of exploration. </p>
    </div>
  </div>
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Stay Curious, Stay in Touch</h5>
      <h6 class="card-subtitle mb-2 text-muted">
        <i class="fa-solid fa-magnifying-glass"></i></h6>
      <p class="card-text">AskFizz, staying curious is not just a choice; it's a celebration of the human spirit. Stay Curious, Stay in Touch,
        and let your questions become threads that weave the fabric of human connection. In this warm community,
        every question is an invitation to understand, connect, and embrace the shared journey of curiosity. </p>
    </div>
  </div>
  <%= image_tag "laptop.png", style: "height: 260px;" %>
</div>
<%= render "shared/footer" %>

app/views/questions/_form.html.erb
<%= simple_form_for [@user, @question], html: { data: { turbo: false } } do |f| %>
  <%= f.text_area :content, id: "question_content", name: "question[content]", required: true %>
  <%= f.hidden_field :asked_to_id, value: @user.id %>
  <div class="submit-question">
    <%= f.input :anonymous,as: :boolean %>
    <%= f.button :submit, 'Submit', class: 'submit-btn' %>
  </div>
<% end %>

app/views/questions/index.html.erb
<div class="show-container">
  <div class="show-question-header">
    <h3>
      Questions
    </h3>
  </div>
  <div class="question-cards-container">
    <% @questions.each do |question| %>
      <div class="question-card">
        <% if question.user.present? %>
          <%= link_to user_question_path(user_id: question.user.id, id: question.id),
              method: :delete,
              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
              class: "delete" do %>
            <i class="fa-solid fa-trash"></i>
          <% end %>
        <% end %>
        <div class="show-questions">
          <h2><%= question.content %></h2>
          <p> <%= question.anonymous ? '' :  'by: ' + question.user&.username %></p>
        </div>
        <div class="answer-btn">
          <%= link_to new_user_question_answer_path(user_id: question.user.id, question_id: question.id), class: "submit-btn" do %>
            <button class="submit-btn">Answer?</button>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    © 2024 AskFizz. All Rights Reserved.
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg" style="background-color:#163020">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
      <%= image_tag('nav-logo.png', alt: 'askfizz logo', class: "nav-logo") %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" style="color:#EEF0E5" aria-current="page" href="<%= users_path %>">Home</a>
        </li>
        <% if current_user.present? %>
          <li class="nav-item">
            <a class="nav-link" style="color:#EEF0E5" href="<%= user_path(current_user) %>">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" style="color:#EEF0E5" href="<%=user_questions_path(current_user) %>">Questions</a>
          </li>
        <% end %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" style="color:#EEF0E5" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Settings
        </a>
        <ul class="dropdown-menu">
          <% if current_user %>
            <li><a class="dropdown-item" style="color:#163020" href="<%= destroy_user_session_path %>" data-turbo-method="delete">Log Out</a></li>
          <% else %>
            <a class="dropdown-item" style="color:#163020" href="<%= new_user_session_path %>">Sign In</a>
          <% end %>
        </ul>
      </li>
    </ul>
  </div>
</div>
</nav>

app/views/users/index.html.erb
<div class="container-user">
  <div class="header-user">
    <h3><i class="fa-solid fa-users" style="color:green; font-size: 45px;"></i></h3>
  </div>
  <div class="card-user-container">
    <% @users.each do |user| %>
      <div class="card-user">
        <% if user.photo.attached? %>
          <%= cl_image_tag user.photo.key, height: 120, width: 120, crop: :fill, class: "index-picture" %>
        <% else %>
          <%= image_tag image_path("user.png"), height: 120, width: 120, crop: :fill, class: "index-picture" %>
        <% end %>
        <p>@<%= link_to user.username, user_path(user) %></p>
      </div>
    <% end %>
  </div>
</div>
<div class="main-index-container">
  <% @users.each do |user|%>
    <% user.answers.order(created_at: :desc).each do |answer| %>
      <div class="question-container">
        <div class="index-pic">
          <% if user.photo.attached? %>
            <%= cl_image_tag user.photo.key, height: 120, width: 120, crop: :fill, class: "index-picture"%>
          <% else %>
            <%= image_tag image_path("user.png"), height: 120, width: 120, crop: :fill, class: "index-picture" %>
          <% end %>
          <p>@<%= link_to user.username, user_path(user) %></p>
        </div>
        <div class="index-text">
          <div class="header-index-text">
            <h2>
              Q: <%= answer.question.content %>
            </h2>
            <p class="time"><em><%= answer.created_at.strftime("%e %b %Y %H:%M:%S%p") %></em></p>
          </div>
          <p>
            <%= answer.content %>
          </p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/search.html.erb
<h1>Search Results</h1>
<% if @users.present? %>
  <ul>
    <% @users.each do |user| %>
      <li><%= user.username %></li>
    <% end %>
  </ul>
<% else %>
  <p>No results found.</p>
<% end %>

app/views/users/show.html.erb
<div class="show-container">
  <div class="profile">
    <div class="index-pic-show">
      <% if @user.photo.attached? %>
        <%= cl_image_tag @user.photo.key, height: 150, width: 150, crop: :fill %>
      <% else %>
        <%= image_tag image_path("user.png"), height: 150, width: 150, crop: :fill %>
      <% end %>
      <div class="details-containter" style="margin-left: 20px;">
        <div class="header-user-names">
          <h3><%= @user.first_name %> <%= @user.last_name %></h3>
          <h4>(@<%= @user.username %>)</h4>
        </div>
        <div class="follow-details">
          <div class="answered-section">
            <h4><%= current_user.answers.count %></h4>
            <p>Answered questions</p>
          </button>
        </div>
        <div class="following-section">
          <button type="button" class="btn btn-follow" data-bs-toggle="modal" data-bs-target="#FollowingModal">
            <h4><%= @user.followings.count %></h4>
          </button>
          <p>Following</p>
        </div>
        <div class="followers-section">
          <button type="button" class="btn btn-follow" data-bs-toggle="modal" data-bs-target="#FollowerModal">
            <h4><%= @user.followers.count %></h4>
          </button>
          <p>Followers</p>
        </div>
      </div>
      <%# modals %>
      <!-- Following-Modal -->
      <div class="modal fade" id="FollowingModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="follow-modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Following</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <% @user.followings.each do |following_user| %>
                <p><%= following_user.username %></p>
              <% end %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
      <!-- Follower-Modal -->
      <div class="modal fade" id="FollowerModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="follow-modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Followers</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <% @user.followers.each do |following_user| %>
                <p><%= following_user.username %></p>
              <% end %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
      <%# modals-end %>
      <% if user_signed_in? && current_user != @user %>
        <div class="follow-links">
          <% if current_user.following?(@user) %>
            <%= button_to "Unfollow", user_relationships_path(@user, current_user), method: :delete, class: "follow-button" %>
          <% else %>
            <%= button_to "Follow", user_relationships_path(@user), method: :post, class: "follow-button" %>
          <% end %>
        </div>
      <% end %>
      <!-- Button trigger modal -->
      <% if @user == current_user %>
        <button type="button" class="edit-profile-button" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
          Edit Profile
        </button>
      <% end %>
      <!-- Modal -->
      <%= simple_form_for @user, html: { data: { turbo: false } } do |f| %>
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Edit Profile</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <%= f.input :first_name, input_html: { class: "user-form" } %>
                <%= f.input :last_name, input_html: { class: "user-form" } %>
                <%= f.input :username, input_html: { class: "user-form" } %>
                <%= f.input :photo, as: :file %>
              </div>
              <div class="modal-footer">
                <%= f.submit "Save", class: "modal-button" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%# separator %>
<div class="question-box">
  <h3>Ask Me!</h3>
  <%= render 'questions/form', question: Question.new %>
</div>
<%# separator %>
<div class="answer-box">
  <div class="answer-title">
    <h3>Answers</h3>
  </div>
  <% @user.answers.order(created_at: :desc).each do |answer| %>
    <div class="answer-card">
      <div class="answer-content-container">
        <div class="question-header">
          <h5><%= answer.question.content %></h5>
          <div class="question-content">
            <% if answer.question.anonymous? %>
              <%# no image since its anonymous %>
            <% elsif answer.question.user.photo.attached? %>
              <%= cl_image_tag answer.question.user.photo.key, height: 25, width: 25, crop: :fill %>
            <% else %>
              <%= image_tag image_path("placeholder.png"), height: 25, width: 25, crop: :fill %>
            <% end %>
            <p> <% if answer.question.anonymous? %>
              <% else %>
                by: @<%= link_to answer.question.user.username, user_path(answer.question.user) %>
              <% end %></p>
          </div>
        </div>
        <p><%= answer.content %></p>
        <p class="time"><em><%= answer.created_at.strftime("%e %b %Y %H:%M:%S%p") %></em></p>
      </div>
    </div>
  <% end %>
</div>